### ISSUE TITLE
Spacial awareness? 

### ISSUE THREAD

**Issue by mattada** [dannowatts/massive-bearded-farts#3]
as we process the impact of a fart classed element, should it auto fill the space? I assume a element like:

`<div class="large fart">...</div>`

Would need to auto fill. 

Suggestion: 
`.large.fart {
  width: 100vw;
  height: 100vh;
}`

Is there any community concern for iOS 7 and under support?

**Comment by erwstout** [comment]
In the past i've noticed that `.large.fart` ignores any `vw` property on iOS7 and under. Maybe changing the class to `.large.fart{ width: 1000% } would work?

**Comment by mattada** [comment]
But wouldn't 1000% simply overpower? I worry about the impact to the user experience of the large fart if its just too strong. 

maybe just 100%?
